In [1]:
import numpy as np

In [2]:
!pip install numpy

In [3]:
np.__version__

'1.25.2'

# Numpy Array Examples

In [34]:
fruits = ['apple', 'banana', 'orange']  #this is a list

In [35]:
vegetables = ['lettuce', 'tomato', 'cabbage']

In [36]:
print(type(fruits), type(vegetables))

<class 'list'> <class 'list'>


In [37]:
# create a 2D numpy array

fruits_vegetables = np.array( [fruits,vegetables] )

fruits_vegetables

array([['apple', 'banana', 'orange'],
       ['lettuce', 'tomato', 'cabbage']], dtype='<U7')

In [38]:
type(fruits_vegetables)

numpy.ndarray

In [11]:
fruits_vegetables_2Dlist = [ fruits,vegetables ]
fruits_vegetables_2Dlist

[['apple', 'banana', 'orange'], ['lettuce', 'tomato', 'cabbage']]

In [12]:
type(fruits_vegetables_2Dlist)

list

In [14]:

fruits_vegetables[0][2]

fruits_vegetables[0,2]  #numpy array can use comma


'orange'

In [15]:
fruits_vegetables_2Dlist[0][2]

'orange'

In [16]:
# first row, 2nd column in 2D array

fruits_vegetables[0,1]

'banana'

In [19]:
# does -ve index work?
fruits_vegetables[-1,-1]
fruits_vegetables[1,-1]

'cabbage'

In [28]:
fruits_price = [0.5, 0.7, 0.9]

In [29]:
vegetables_price = [1.5, 1.7, 1.9]

In [40]:
fruits_vegetables_price = np.array( [fruits, fruits_price, vegetables, vegetables_price] )

fruits_vegetables_price

# all the elements are string, cannot mix

array([['apple', 'banana', 'orange'],
       ['0.5', '0.7', '0.9'],
       ['lettuce', 'tomato', 'cabbage'],
       ['1.5', '1.7', '1.9']], dtype='<U32')

In [41]:
fruits_vegetables_prices = np.array( [fruits_price, vegetables_price])
fruits_vegetables_prices

#all the elements are int

array([[0.5, 0.7, 0.9],
       [1.5, 1.7, 1.9]])

# Array Properties

In [43]:
fruits_vegetables.ndim #number of dimensions in array

2

In [45]:
fruits_vegetables.shape   #rows, columns

(2, 3)

In [46]:
fruits_vegetables.size   #total number of items

6

In [47]:
fruits_vegetables.dtype   #type of the items stored

dtype('<U7')

In [48]:
new_array1 = np.random.ranf(5)
new_array1

array([0.62463958, 0.93941474, 0.79246737, 0.47150366, 0.54584296])

# Work with numpy arrays

In [50]:
# axis

n1 = [10,20,30,40]
n2= [1000,2000,3000,4000]

nArr = np.array([n1,n2])

nArr

array([[  10,   20,   30,   40],
       [1000, 2000, 3000, 4000]])

In [53]:
nArr.mean()

1262.5

In [55]:
range = nArr.max() - nArr.min()
range

3990

In [59]:
Q3 = np.percentile(nArr,75)
Q3

2250.0

In [52]:
nArr.mean(axis=0) #compute mean along the direction of rows ==> columns

array([ 505., 1010., 1515., 2020.])

In [60]:
nArr.mean(axis=1) #compute mean along the direction of cols ==> rows

array([  25., 2500.])

In [67]:
#min of the first row

nArr.min(axis=1)[0]

nArr[0].min()

10

# Matplotlib